In [1]:
import numpy as np

In [2]:
# bagaimana dengan list kalkulasi bekerja

list_berat_badan = [45, 47, 50, 65, 71, 89, 90]
list_tinggi_badan = [1.7, 1.6, 1.5, 1.7, 1.8, 1.65, 1.75]

print(list_berat_badan + list_tinggi_badan)
print(list_berat_badan * list_tinggi_badan) #list tidak bisa dikalikan, akan menyebabkan ERROR

[45, 47, 50, 65, 71, 89, 90, 1.7, 1.6, 1.5, 1.7, 1.8, 1.65, 1.75]


TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
# cara membuat numpy array dari list
np_berat_badan = np.array(list_berat_badan)

np_tinggi_badan = np.array(list_tinggi_badan)

#cek type nya
print(type(np_berat_badan)) 
print(type(np_tinggi_badan))

In [ ]:
#membuat numpy array dari awal
np_berat_badan = np.array([45, 47, 50, 65, 71, 89, 90])

np_tinggi_badan = np.array([1.7, 1.6, 1.5, 1.7, 1.8, 1.65, 1.75])

print(len(berat_badan)) # mengecek panjang element
print(len(tinggi_badan)) # mengecek panjang element

In [ ]:
#Menghitung BMI

BMI = np.round(np_berat_badan / np_tinggi_badan ** 2, 2) # cara menyederhanakan bilangan desimal
BMI

In [ ]:
# Slicing BMI index 0 - 2
BMI[0:3]

In [ ]:
# bagaimana dengan numpy kalkulasi bekerja

print(np_berat_badan + np_tinggi_badan) # menjumlahkan element-nya satu per satu (metrics calculation)

print(np_berat_badan * np_tinggi_badan) # mengkalikan element-nya satu per satu (metrics calculation)

In [ ]:
# Slicing numpy array dengan menggunakan comparison operators

normal_underweight_1 = BMI < 30 # hasilnya berupa boolean values
normal_underweight_2 = BMI[BMI < 30] # hasilnya berupa nilai aslinya
print(normal_underweight_1)
print(normal_underweight_2)


In [ ]:
# membuat 2D numpy Array

tinggi_berat = [[45, 1.7], [47, 1.6], [50, 1.5], [65, 1.7]]

np_tinggi_berat = np.array(tinggi_berat)
np_tinggi_berat

In [ ]:
# dari np_tinggi_berat, Mencari nilai rata2 dari berat badan saja

np.mean(np_tinggi_berat[:, 0])

# dari np_tinggi_berat, Mencari nilai rata2 dari tinggi badan saja

np.mean(np_tinggi_berat[:, 1])

In [ ]:
# Merubah tinggi dari meter menjadi meter
tinggi_cm = np_tinggi_berat[:, 1] * 100
tinggi_cm


In [ ]:
# menambahkan 2kg ke masing2 berat badan

berat_2kg = np_tinggi_berat[:, 0] + 2
berat_2kg

In [3]:
# 2D Numpy Array


USA = 21.44 # Amerika Serikat
CHN = 14.14 # Cina
JPN = 5.15 # Jepang
DE = 3.86 # Jerman
IND = 2.94 # India
GBR = 2.83 # Britania Raya
FRA = 2.71 # Perancis
ITA = 1.99 # Italia
BRA = 1.85 # Brazil
CAN = 1.73 # Kanada

negara = np.array([["Amerika Serikat", USA], ["Cina", CHN], ["Jepang", JPN], ["Jerman", DE], 
          ["India", IND], ["Britania Raya", GBR], ["Perancis", FRA], ["Italia", ITA], 
          ["Brazil", BRA], ["Kanada", CAN]])

negara.shape #mengetahui bentuk dataset, rows dan columns
negara

array([['Amerika Serikat', '21.44'],
       ['Cina', '14.14'],
       ['Jepang', '5.15'],
       ['Jerman', '3.86'],
       ['India', '2.94'],
       ['Britania Raya', '2.83'],
       ['Perancis', '2.71'],
       ['Italia', '1.99'],
       ['Brazil', '1.85'],
       ['Kanada', '1.73']], dtype='<U32')

In [13]:
GDP = negara[:, 1].astype(float)
np.mean(GDP)

5.863999999999999

In [125]:
# subset Jerman dan value nya
negara[3, :]

array(['Jerman', '3.86'], dtype='<U32')

In [126]:
# subset Jerman dan value nya
negara[6, :]

array(['Perancis', '2.71'], dtype='<U32')

In [127]:
# subset "Amerika Serikat"
negara[0, 0]

'Amerika Serikat'

In [52]:
#Subset "Jepang"

negara[2, 0]

'Jepang'

In [128]:
# Subset GDP dari "India"
negara[4, 1]

'2.94'

In [129]:
# Subset seluruh nama negaranya saja

negara[:, 0]

array(['Amerika Serikat', 'Cina', 'Jepang', 'Jerman', 'India',
       'Britania Raya', 'Perancis', 'Italia', 'Brazil', 'Kanada'],
      dtype='<U32')

In [90]:
# Membuat numpy array dengan np.arrange()

x = np.arange(1, 11) 


y = np.arange(11, 21)

print(x)
print(y)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [92]:
# complex calculation dengan numpy. Ikuti rules PEMDAS

"""PEMDAS

P = Paranthesis ()
E = Exponentiation **
M = Multiplication *
D = Division /
A = Addition +
S = Substraction -
"""

(y * x) / 2 ** 2

array([ 2.75,  6.  ,  9.75, 14.  , 18.75, 24.  , 29.75, 36.  , 42.75,
       50.  ])